name: Consolidated Cleanup Tags and Releases
description: Clean up git tags and releases, with mode-specific behavior for GitHub vs ACT

runs:
  using: composite
  steps:
    - name: Delete all releases (GitHub mode)
      if: ${{ !github.event.act }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh api repos/${{ github.repository }}/releases --jq '.[].id' | xargs -I {} gh api repos/${{ github.repository }}/releases/{} -X DELETE || true
