name: Consolidated Kodi Check
description: Check for Kodi project, GitHub-only (skipped in ACT mode)

outputs:
  is_kodi:
    description: Whether project is a Kodi addon
    value: ${{ steps.check.outputs.is_kodi }}
  kodi_project_name:
    description: Kodi project name
    value: ${{ steps.check.outputs.kodi_project_name }}
  kodi_directory:
    description: Kodi addon directory
    value: ${{ steps.check.outputs.kodi_directory }}

runs:
  using: composite
  steps:
    - name: Check for Kodi project (GitHub only)
      if: ${{ !github.event.act }}
      id: check
      uses: ./.github/actions/check-kodi-project

    - name: Set dummy outputs (ACT mode)
      if: ${{ github.event.act }}
      shell: bash
      run: |
        echo "is_kodi=false" >> $GITHUB_OUTPUT
        echo "kodi_project_name=" >> $GITHUB_OUTPUT
        echo "kodi_directory=" >> $GITHUB_OUTPUT
