name: 'Create test branch'
description: 'Create a test branch for CI'
inputs:
  test_branch:
    description: 'The test branch name (e.g., ci/act-... or ci/gha-...)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Create and push test branch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TEST_BRANCH: ${{ inputs.test_branch }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config --local url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        # Delete remote branch if it exists from previous test runs
        git push origin --delete $TEST_BRANCH 2>/dev/null || true
        # Create fresh local branch from main
        git checkout -b $TEST_BRANCH
        git push -u origin $TEST_BRANCH