name: 'Setup Environment'
description: 'Install uv, set up venv, and configure PATH'
runs:
  using: 'composite'
  steps:
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash
    - name: Set up venv
      run: |
        export PATH="$PATH:/root/.local/bin"
        uv venv /tmp/venv
        export UV_VENV=/tmp/venv
      shell: bash