name: 'Run PSR Locally'
description: 'Execute PSR with template rendering (no actual release)'
inputs:
  fixture_dir:
    description: 'Directory to run PSR in'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Install PSR
      run: |
        source /tmp/venv/bin/activate
        uv pip install python-semantic-release
      shell: bash
      working-directory: ${{ github.workspace }}
    - name: Run PSR (render templates, no release/push)
      run: |
        source /tmp/venv/bin/activate
        cd ${{ inputs.fixture_dir }}
        python-semantic-release publish --ci false --no-push --no-tag --no-vcs-release 2>&1 | tee psr-run.log
      shell: bash
      working-directory: ${{ github.workspace }}