name: 'Run PSR Locally'
description: 'Execute PSR with template rendering (no actual release)'
inputs:
  fixture_dir:
    description: 'Directory to run PSR in'
    required: false
    default: '.'
  force:
    description: 'Force version bump level (major, minor, patch, or leave empty for automatic)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install PSR
      run: |
        source /tmp/venv/bin/activate
        uv pip install python-semantic-release
      shell: bash
      working-directory: ${{ github.workspace }}
    - name: Run PSR (render templates, create local tags, no GitHub push)
      run: |
        source /tmp/venv/bin/activate
        cd ${{ inputs.fixture_dir }}
        force_arg=""
        if [ -n "${{ inputs.force }}" ]; then
          force_arg="--${{ inputs.force }}"
        fi
        python-semantic-release version $force_arg --changelog --commit --tag --no-push --no-vcs-release 2>&1 | tee psr-run.log
      shell: bash
      working-directory: ${{ github.workspace }}