name: 'Run PSR Locally'
description: 'Execute PSR with dry-run'
inputs:
  fixture_dir:
    description: 'Directory to run PSR in'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Install PSR
      run: |
        source /tmp/venv/bin/activate
        uv pip install python-semantic-release
      shell: bash
      working-directory: ${{ github.workspace }}
    - name: Run PSR dry-run
      run: |
        source /tmp/venv/bin/activate
        cd ${{ inputs.fixture_dir }}
        python-semantic-release --noop version > psr-dry-run.log
      shell: bash
      working-directory: ${{ github.workspace }}