name: 'Run Pre-PSR Tests'
description: 'Run pre-PSR integration tests'
runs:
  using: 'composite'
  steps:
    - name: Run pre-PSR integration tests
      run: |
        source /tmp/venv/bin/activate
        pytest tests/integration/pre_psr/ -v
      shell: bash