name: Consolidated Kodi Zip
description: Build Kodi addon zip file and upload artifact (runs in both GitHub and ACT modes)

inputs:
  kodi_project_name:
    description: Kodi project name
    required: true
  kodi_directory:
    description: Kodi addon directory
    required: true
  version:
    description: Version to build
    required: true
  phase:
    description: Release phase name
    required: true

runs:
  using: composite
  steps:
    - name: Build Kodi zip
      uses: ./.github/actions/build-kodi-zip
      with:
        kodi_project_name: ${{ inputs.kodi_project_name }}
        kodi_directory: ${{ inputs.kodi_directory }}
        version: ${{ inputs.version }}
        phase: ${{ inputs.phase }}
    - name: Upload rendered templates
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: rendered-templates-${{ inputs.phase }}
        path: |
          CHANGELOG.md
          ${{ inputs.kodi_directory }}/addon.xml
