name: 'Build Kodi Addon ZIP'
description: 'Create ZIP archive of Kodi addon and upload as artifact'
inputs:
  kodi_project_name:
    description: 'Name of the Kodi project'
    required: true
  kodi_directory:
    description: 'Directory path of the Kodi addon'
    required: true
  version:
    description: 'Version string for the ZIP filename'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build Kodi addon ZIP
      run: |
        mkdir -p artifacts
        zip -r artifacts/${{ inputs.kodi_project_name }}-${{ inputs.version }}.zip ${{ inputs.kodi_directory }}
      shell: bash
    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: kodi-addon-zip
        path: artifacts/${{ inputs.kodi_project_name }}-${{ inputs.version }}.zip
