name: Generate and Push Commits
description: Generate test commits for a specific phase and push to remote

inputs:
  phase:
    description: The phase number (0, 1, 2, etc.)
    required: true
  branch:
    description: The branch name to push to
    required: true
  git-url:
    description: Base git URL (e.g., https://github.com or http://localhost:3000)
    required: false
    default: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}

runs:
  using: composite
  steps:
    - name: Generate phase commits
      shell: bash
      run: |
        python tools/generate_commits.py --phase ${{ inputs.phase }} .
    - name: Push commits to remote
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GIT_URL: ${{ inputs.git-url }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Only set GitHub auth if using GitHub (not gitea)
        if [[ "$GIT_URL" == *"github.com"* ]]; then
          git config --local url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        fi
        
        # Push to the remote repository (gitea or GitHub)
        git push "$GIT_URL/test-repo.git" HEAD:${{ inputs.branch }}
